### ISSUE TITLE
Drop unsupported node versions

### ISSUE THREAD

**Issue by Ayc0** [expressjs/generator#260] opened 2020-05-03 00:51 UTC
AppVeyor | Travis
-|-
![image](https://user-images.githubusercontent.com/22725671/80895765-7dc1a280-8cb6-11ea-99b5-455781d3b333.png) | ![image](https://user-images.githubusercontent.com/22725671/80895769-8ca85500-8cb6-11ea-842b-68e6b0744b1b.png)

According to the tests done automatically in the CI, express-generator only has tests for deprecated versions of node.

Should we remove those versions and use instead the supported ones (aka node 10, 12, 13 and 14)?
![image](https://user-images.githubusercontent.com/22725671/80895917-beb9b700-8cb6-11ea-9c14-399bd39d7f3d.png)

**Comment by dougwilson** [comment] 2020-05-03 00:53
Duplicate of #241

**Closed by dougwilson** 2020-05-03 00:53 UTC

**Comment by dougwilson** [comment] 2020-05-03 00:54
If you are interested, we are working on a re-work of the generation for express apps over at https://github.com/wesleytodd/create-express-app
