### ISSUE TITLE
Nodemon still doesn't seem to work

### ISSUE THREAD

**Issue by teknoalex** [expressjs/generator#235] opened 2019-07-23 15:33 UTC
I have a freshly generated express app that works perfectly fine.
But I can't get the auto restart on save to work. I am using:

`"start" : "nodemon ./bin/www"`

but I always need to press rs after saving a file, it never automatically restarts.

I know this was already mentioned once but I couldnt solve it.

**Comment by Drozerah** [comment] 2019-09-27 18:19
Same issue "start": "nodemon ./bin/www" do not refresh page in the browser

**Comment by dougwilson** [comment] 2019-09-27 18:24
I'm not familiar with nodemon, so not sure why it wouldn't work or what a fix would be. The best way to get it working is probably to either:

(a) fully describe all the steps needed to reproduce the issue, noting versions used, what commands to run from zero to issue, etc.

Or

(b) a pull request with the suggested fix.

**Comment by dpawson905** [comment] 2019-11-02 11:20
Are you by chance running windows? If so try creating a new script: "dev": "nodemon" and it'll work just fine.

**Comment by jonchurch** [comment] 2020-02-01 06:04
I was unable to reproduce this issue. Closing this for now, please reopen if you can help us reproduce this behavior 👍

**Closed by jonchurch** 2020-02-01 06:04 UTC
Labels: awaiting more info
