### ISSUE TITLE
nunjucks support official alongside handlebars, etc.

### ISSUE THREAD

**Issue by coderam** [expressjs/generator#182] opened 2017-11-20 02:00 UTC
Hi, can you please add nunjucks support alongside Handlebars to the generator? That way people coming over from Django can use something familiar.

Thanks!!

**Comment by dougwilson** [comment] 2017-11-20 02:10
Absolutely! #156 is the tracking issue for this, so closing this as a duplicate of #156

**Closed by dougwilson** 2017-11-20 02:10 UTC
